Nombre=input("Ingrese el nombre de el estudiante:")
print("""El estudiante sera calificado de la sigiente manera
    nivel de calificacion 
    1.0-2.9= Bajo
    3.0-4.0= medio
    4.1-4-7= alto
    4.8-5.0= superior 
¡RECUERDA! Si la nota es superior a 3.0 el estudiante aprueba la asignatura, de lo contrario reprueba""")
print("Primera asignatura")
Asg1= int(input("Ingrese la primer asignatura:"))
n1=float(input("Ingrese la primer nota del estudiante:"))
n2=float(input("Ingrese la segunda nota del estudiante:"))
n3=float(input("Ingrese la tercer nota del estudiante:"))
pro1=(n1+n2+n3/3)
print(f'El promedio de la asignatura {Asg1} del estudiante:,{Nombre},es:,{pro1}')
print("Segunda asignatura")
Asg2= int(input("Ingrese la segunda asignatura:"))
no1=float(input("Ingrese la primer nota del estudiante:"))
no2=float(input("Ingrese la segunda nota del estudiante:"))
no3=float(input("Ingrese la tercer nota del estudiante:"))
prom2=(no1+no2+no3/3)
print('El promedio de la asignatura"{Asg2}"del estudiante:",{Nombre},"es:",{prom2}')
print("Tercer asignatura")
Asg3= int(input("Ingrese la segunda asignatura:"))
not1=float(input("Ingrese la primer nota del estudiante:"))
not2=float(input("Ingrese la segunda nota del estudiante:"))
not3=float(input("Ingrese la tercer nota del estudiante:"))
prome3=(not1+not2+not3/3)
print('El promedio de la asignatura"{Asg3}"del estudiante:",{Nombre}"es:",{prome3}')
print("Cuarta asignatura")
Asg4= int(input("Ingrese la segunda asignatura:"))
nota1=float(input("Ingrese la primer nota del estudiante:"))
nota2=float(input("Ingrese la segunda nota del estudiante:"))
nota3=float(input("Ingrese la tercer nota del estudiante:"))
promed4=(nota1+nota2+nota3/3)
print('El promedio de la asignatura"{Asg4}"del estudiante:",{Nombre},"es:",{promed4}')
print("Quinta asignatura")
Asg5= int(input("Ingrese la segunda asignatura:"))
nt1=float(input("Ingrese la primer nota del estudiante:"))
nt2=float(input("Ingrese la segunda nota del estudiante:"))
nt3=float(input("Ingrese la tercer nota del estudiante:"))
promedio5=(nt1+nt2+nt3/3)
print('El promedio de la asignatura"{Asg5},"del estudiante:",{Nombre},"es:",{promedio5}')
print("------------------------------------------------------------")
print("Promedio Final del estudiante")
pf=(pro1+prom2+prome3+promed4+promedio5/5)
print("El promedio final del estudiante:",Nombre,"es:",pf)

