"""print("Actividad 1")
cadena1= "El conocimiento es poder"
buscar_subcadena1= cadena1.find("conocimiento")
buscar_subcadena= cadena1.find ("poder")
print(buscar_subcadena1)
print(buscar_subcadena)
print("****************************************************************")
print("Acvtividad 2")
tex1= "La practica hace al maestro"
buscar_subcadena1= tex1.find("practica")
buscar_subcadena= tex1.find ("maestro")
print(buscar_subcadena1)
print(buscar_subcadena)
print("****************************************************************")
print("Actividad 3")
frase1=input("Ingrese una frase:")
bus= input("Ingrese una palabra que desee buscar en la frase anterior:")
print(frase1.find(bus))"""
print("****************************************************************")
print("Actividad 4")
test = "Doña Uzeada de Ribera Maldonado de Bracamonte y Anaya era baja, rechoncha, abigotada. Ya no existia razon para llamar talle al suyo. Sus colores vivos, sanos, podian mas que el albayalde y el soliman del afeite, con que se blanqueaba por simular melancolias. Gastaba dos parches oscuros, adheridos a las sienes y que fingian medicamentos. Tenia los ojitos ratoniles, maliciosos. Sabia dilatarlos duramente o desmayarlos con recato o levantarlos con disimulo. Caminaba contoneando las imposibles caderas y era dificil, al verla, no asociar su estampa achaparrada con la de ciertos palmipedos domesticos. Sortijas celestes y azules le ahorcaban las falanges"
buscar= test.find("Sabia")
print(buscar)
bus= test.find("Caminaba")
print(bus)
busc=test.find("falanges")
print(busc)
print(test[459:655])
print("*****************************************************************")
print("EXTRAER")
tex2= "Simplemente como conjetura, imagine el lector una inversion de las circunstancias: que Hamas permitiese a los israelies vivir en cantones desparramados e invariables, virtualmente separados unos de otros, y en alguna pequeña parte de Jerusalen, mientras los palestinos construyen enormes asentamientos y proyectos de infraestructura para apoderarse de las tierras y los recursos de Israel, Y que, ademas Hamas acepte llamar a esos fragmentos un Estado. Si se hicieran propuestas para esta empobrecida categoria de Estado, nosotros nos sentiriamos, con razon, horrorizados. Pero con ese tipo de propuestas, la posicion de Hamas seria esencialmente igual a la de Estados Unidos e Israel."
buscar1= tex2.find("imagine")
print(buscar1)
buscar2= tex2.find("asentamientos")
print(buscar2)
print("*****************************************************************")
print("Actividad 5")
nombre=input("Ingrese el numero del estudiante:")
nota1= float(input("Ingrese la nota 1 del estudiante:"))
nota2= float(input("Ingrese la nota 2 del estudiante:"))
nota3=float(input("Ingrese la nota 3 del estudiante:"))
final= (nota1*0.20)+(nota2*0.30)+(nota3*0.50)
print("El estudiante",nombre,"tiene una nota final de:",final)
if final >= 3.0:
    print("El estudiante aprobo")
else:
    print("El estudiante reprobo")