# # print("Ejercicio 1")
# # num1= int(input("Ingrese el primer numero para sumar:"))
# # num2= int(input("Ingrese el segundo numero para sumar:"))
# # result= num1+num2
# # print("La suma de los dos numeros es:",result)
# # print("*****************************************************************")
# # print("Ejercicio 2")
# n1= int(input("Ingrese el primer numero para restar:"))
# n2=int(input("Ingrese el segundo numero para restar:"))
# res= n1-n2
# print("La resta del primer numero menos el segundo es:",res)
# print("******************************************************")
# print("Ejercicio 3")
# nu1= int(input("Ingrese el primer numero para multiplicar:"))
# nu2=int(input("Ingrese el segundo numero para multiplicar:"))
# resu= n*n2
# print("El resultado de sue multiplicacion es:",resu)
# print("*******************************************************")
# print("Ejercicio 4")
# nume1= int(input("Ingrese el primer numero para dividir:"))
# nume2=int(input("Ingrese el segundo numero para dividir:"))
# resulta= nume1/nume2
# print("El resultado de su division es:",resulta)
# print("*******************************************************")
# print("Ejercicio 5")
# nombre= input("Ingrese su nombre: ")
# apellido= input("Ingrese su apellido: ")
# print(f"Buen dia estimado usuario su nombre es: ",nombre,apellido)
# print("*******************************************************")
# print("Ejercicio 6")
# nombre1= input("Ingrese su nombre: ")
# print(nombre1[0])
# print("La primer letra de su nombres es:",nombre1[0])
# print("*******************************************************")
# print("Ejercicio 7")
# pal= input("Ingrese una palabra : ")
# print(pal[-1])
# print("La ultima letra de su palabra es:",pal[-1])
# print("*******************************************************")
# print("Ejercicio 8")
# base= int(input("Ingrese el numero de base de su rectangulo: "))
# altura= int(input("Ingrese el numero de altura de su rectangulo:"))
# area= base*altura
# print("El area de su rectangulo es:",area)
# print("*******************************************************")
# print("Ejercicio 9")
# año= int(input("Ingrese su año de nacimiento: "))
# edad= (2025-año)
# print("Su edad es:",edad)
# print("*******************************************************")
# print("Ejercicio 10")
# usuario= input("Ingrese su nombre de usuario:")
# dominio= input("Ingrese un dominio:")
# direccion= (usuario+"@"+dominio)
# print("Su direccion de correo electronico es:",direccion)
# print("*******************************************************")
# print("Ejercicio 11")
# name=(input("Ingrese su nombre:"))
# print(len("name"))
# print("Su nombre tiene:",len(name),"letras")
# print("********************************************************")
# print("Ejercicio 12")
# pala1= input("Ingrese la primer palabra:")
# pala2= input("Ingrese la segunda palabra:")
# palabrac= (pala1+pala2)
# print("Las dos palabras unidas son:",palabrac)
# print("********************************************************")
# print("Ejercicio 13")
# pa= input("Ingrese la palabra:")
# print(pa[1])
# print("La segunda letra de su palabra es:",pa[1])
# print("********************************************************")
# print("Ejercicio 14")
# pl= input("Ingrese la palabra:")
# pla=pl[0:3]
# print("Las tres primeras letras de su palabra son:",pla)
# print("********************************************************")
# print("Ejercicio 15")
# al= input("Ingrese la palabra:")
# pb=(al[::-1])
# print("Las letras de su palbra en orden inverso son:",al[::-1])
# print(suma)print("********************************************************")
# print("Ejercicio 16")
# nr1= int(input("Ingrese el primer numero:"))
# nr2= int(input("Ingrese el segundo numero:"))
# suma=(nr1+nr2)
# resta=(nr1-nr2)
# mult=(nr1*nr2)
# divi=(nr1/nr2)
# print(resta)
# print(mult)
# print(divi)
# print("El resultado de sus operaciones es: Suma:",suma,"Resta:",resta,"Multiplicacion:",mult,"y Division:",divi)
# print("********************************************************")
# print("Ejercicio 17")
# no1= int(input("Ingrese un numero:"))
# doble= (no1*2)
# print("El doble de su numero es:",doble)
# print("********************************************************")
# print("Ejercicio 18")
# n_m= int(input("Ingrese un numero"))
# mitad= (n_m/2)
# print("La mitad de su numero es:",mitad)
# print("********************************************************")
# print("Ejercicio 19")
# frase= input("Ingrese una frase para saber cuantos caracteres tiene:")
# print("La cantidad de caracteres de su frase son:",len(frase))
# print("********************************************************")
# print("Ejercicio 20")
# plr=input("Ingrese una palabra:")
# conca=(plr+plr+plr)
# print(conca)
# print("**********************************************************")
# print("Ejercicio 21")
# lb= input("Ingrese una palabra:")
# print(lb[0:2], lb[3:])
# print("**********************************************************")
# print("Ejercicio 22")
# bra= input("Ingrese una palabra con cantidad de letras impar:")
# medio= len(bra)//2
# print("La letra del medio de su palabra es:",bra[medio])
# print("**********************************************************")
# print("Ejercicio 23")
# pab= input("Ingrese una palabra ")
# print(pab[0:11])
# print("Las 10 primeras letras de su palabra son:",pab[0:11])
# print("**********************************************************")
# print("Ejercicio 24")
# nro= int(input("Ingrese un numero para potenciar al cuadrado:"))
# cuadrado= (nro*nro)
# print("El cuadrado de su numero es:",cuadrado)
print("**********************************************************")
print("Ejercicio 25")
ro1= int(input("Ingrese el primer numero:"))
ro2= int(input("Ingrese el segundo numero:"))








